### ISSUE TITLE
lxml dependency and PyPi

### ISSUE THREAD

**Issue by flavianh** [skimhub/pyToXml#10]
I can't "pip install" lxml<3.0.2.
The package you posted on PyPi uses lxml 2.x, the one on GitHub uses lxml == 3.0.2.
When I run "pip install pyToXml" it fails (compilation problem). I had to clone your repository and "python setup.py install" it.
Since it would be more practical to use pip, could you update your package?
Thanks

Configuration: Windows 64 bit, with Python 2.7 32 bit

**Comment by minimal** [comment]
Hi, sorry for the old PyPi version, I got ownership of the package on PyPi transferred to me yesterday and I just pushed version 1.1.0.
